name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-20.04
        job_name:
          - linux_openresty

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 90

    steps:
      - name: Check out APISIX plugins
        uses: actions/checkout@v3

      - name: Check out APISIX repo
        run: |
          sudo make init_apisix
          sudo make patch_apisix

      - name: Install custom module
        run: |
          sudo make install

      - name: Launch APISIX common services
        run: |
          sudo make ci-env-up project_compose_ci=ci/pod/docker-compose.common.yml
        working-directory: workbench

      - name: Linux Get dependencies
        run: |
          sudo apt install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl libpcre3 libpcre3-dev libldap2-dev

      - name: Linux Before install
        run: |
          sudo ./ci/${{ matrix.job_name }}_runner.sh before_install

          # TODO: use a fix release once they have created one.
          # See https://github.com/Tongsuo-Project/Tongsuo/issues/318
          git clone https://github.com/api7/tongsuo --depth 1
          cd tongsuo
          ./config shared -enable-ntls -g --prefix=/usr/local/tongsuo
          make -j2
          sudo make install_sw
        working-directory: workbench

      - name: Linux Do install
        run: |
          export OR_PREFIX=/usr/local/openresty-debug
          export openssl_prefix=/usr/local/tongsuo
          export zlib_prefix=$OR_PREFIX/zlib
          export pcre_prefix=$OR_PREFIX/pcre

          export cc_opt="-DNGX_LUA_ABORT_AT_PANIC -I${zlib_prefix}/include -I${pcre_prefix}/include -I${openssl_prefix}/include"
          export ld_opt="-L${zlib_prefix}/lib -L${pcre_prefix}/lib -L${openssl_prefix}/lib64 -Wl,-rpath,${zlib_prefix}/lib:${pcre_prefix}/lib:${openssl_prefix}/lib64"
          sudo ./ci/${{ matrix.job_name }}_runner.sh do_install
          openresty -V
        working-directory: workbench

      - name: Run test case
        run: |
          sudo ./ci/utils/linux-common-runnner.sh run_case
        working-directory: workbench
